### ISSUE TITLE
How use DataTable DOM

### ISSUE THREAD

**Issue by rafiul** [zepernick/Codeigniter-DataTables#1]
I want to use below  DOM but how?
"sDom": '<"top">rt<"bottom"i><"clear">',

**Comment by zepernick** [comment]
I would recommend visiting the [DataTables](http://datatables.net/reference/option/dom) site for docs on the options in the JS library.  The property is now called `dom` in 1.10.  You can also ask specific questions about the DataTable JS library in their [forum](http://datatables.net/forums/categories/free-community-support)
