### ISSUE TITLE
Version codeiginiter?

### ISSUE THREAD

**Issue by huynn109** [zepernick/Codeigniter-DataTables#13]
I can't run with CI v2.2.3? 

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>

<p>Message:  Invalid argument supplied for foreach()</p>

<p>Filename: libraries/Datatable.php</p>

<p>Line Number: 97</p>

**Comment by zepernick** [comment]
Hi huynn,

Which version of the library are you running?  That line number is a comment in the current version.  It should still work in CI 2.  Also, can you provide your implementation and the javascript that is setting up your DataTable?

**Comment by huynn109** [comment]
I'm using Javascript and library download at http://www.paulzepernick.com/ci-zepernick/.
CI 3.0.2 -> OK
CI 2.2.3 -> Issue

**Comment by kushanz** [comment]
I'm using CI 3.05. and i got the same error like huynn109
