### ISSUE TITLE
Custom search in ajax data

### ISSUE THREAD

**Issue by iprastha** [zepernick/Codeigniter-DataTables#14]
Hi, first of all a great and very useful library!
I have a custom search in my datatable using the ajax.data implementation, something like this:

``` javascript
$('#mytable').dataTable( {
        processing: true,
        serverSide: true,
        ajax: {
            "url"  : "myajaxurl.php",
            "type" : "POST",
            "data"   : function (d){
                d.my_custom_filter = $('#my_custom_filter').val();
            }
        }, ...
```

How do I pass the "my_custom_filter" value into the database query as an additional where statement ?

Thank You

**Comment by zepernick** [comment]
@iprastha  you can accomplish this in the whereClauseArray method..  Here is [another issue](https://github.com/zepernick/Codeigniter-DataTables/issues/12) that has an example of how to do it

**Comment by iprastha** [comment]
Thanks! Got it to work now using the example given in that post.
