### ISSUE TITLE
DatatableModel implemented class cannot extend CI_model

### ISSUE THREAD

**Issue by gfiore88** [zepernick/Codeigniter-DataTables#2]
If I extend CI_model and implement DatatableModel all the methods that are not directly linked with datatableModel don't work.

In short, loading page goes in escape with a 500 error.

If i take out the implements clause the page suddenly works. Why is that?

**Comment by zepernick** [comment]
My guess is that you don't have all of the methods from the DatatableModel implemented.  You have to provide a default implementation even if you are not using the method.

At a minimum, the only method that cannot return a NULL is fromTableStr().  This is what a very basic implementation would look like

``` php
    class store_dt extends CI_Model implements DatatableModel{

        /**
         * @ return
         *      Expressions / Columns to append to the select created by the Datatable library
         */
        public function appendToSelectStr() {
                return NULL;
        }

        public function fromTableStr() {
            return 'MyTable';
        }

        /**
         * @return
         *     Associative array of joins.  Return NULL or empty array  when not joining
         */
        public function joinArray(){
            return NULL;
        }

    /**
     * 
     *@return
     *  Static where clause to be appended to all search queries.  Return NULL or empty array
     * when not filtering by additional criteria
     */
        public function whereClauseArray(){
            return NULL;
        }
   }
```

Let me know if that solves the problem.

**Comment by zepernick** [comment]
Have not heard back in over 2 weeks and this was not a bug.

**Comment by servogod85** [comment]
Actually We fixed the problem. The interface was not being loaded for some strange reason. That is, if you use both extend CI_Model and implements Datablae, for some strange reason, the datable inteface will not be loaded. If you put the following code befora declaring:

```
get_instance()->load->iface('Datatable');
```

Then in MY_Loader you need to implement iface:

```
    public function iface($name){
        require_once APPPATH.'libraries/'.$name.'.php';
    }
```

Then bothe the extends and the implements will finally works.
Cheers,

Salvo and Giovanni

**Comment by zepernick** [comment]
Hi Salvo and Giovanni,

Thank you for getting back.  I would like to look into this further, but I have not seen this same issue occur.  Are yoy using HMVC?

**Comment by servogod85** [comment]
Yes we are, Our controllers extend a MY_Core controller which then extends the CI_CONTROLLER, but our models extend directly CI_Model. The problems lies in the fact that this model has to extend  CI_Model and implement Datatable. Now, some controllers use the regular methods, while other controllers access the same model through the Datatable interface. By extending the interface, the regular methods that have nothing do with the datatable methods do not work anymore. It is very strange indeed.

**Comment by servogod85** [comment]
Here is an example code:

```

get_instance()->load->iface('Datatable');

class Gara_model extends CI_Model implements DatatableModel {


    public function elimina_gara($id_gara) {
       ....
    }

    public function elimina_elabora_gara($id) {
        ...
    }

    public function getGareElaborabili() {
    ....
    }

//*******************************************************************************************************


    public function appendToSelectStr() {
        return array(
            ...
        );
    }

    public function fromTableStr() {
        return 'elabora_gara e';
    }

    public function joinArray() {
        return array(
            ....
            );
    }

    public function whereClauseArray() {

        return null;
    }

    /*I also implemented this for personal use*/
    public function likeClauseArray() {
        $params = array(
          ....
        );

        return $params;
    }



}

```

All the methods above the asterisks will not work if the interface is not loaded.

**Comment by boopathit** [comment]
Hi... you said...

Then in MY_Loader you need to implement iface:
 public function iface($name){
        require_once APPPATH.'libraries/'.$name.'.php';
    }

Where in this MY_Loader....?
I'm a beginner to Codeigniter.
so please help?

Where to put the above code?
