### ISSUE TITLE
Cannot access protected property CI_DB_mysqli_driver

### ISSUE THREAD

**Issue by ErvinLlojku** [zepernick/Codeigniter-DataTables#6]
A PHP Error was encountered

Severity: Error

Message: Cannot access protected property CI_DB_mysqli_driver::$_protect_identifiers

Filename: libraries/Datatable.php

Line Number: 331

**Comment by zepernick** [comment]
Hi @ErvinLlojku ,

I just pushed [release 1.2](https://github.com/zepernick/Codeigniter-DataTables/releases/tag/v1.2) that fixes this issue.  Thank you for reporting it!

Paul

**Comment by ErvinLlojku** [comment]
Hi Paul,

You have done a great work!Thank you!

Cheers!

**Comment by zepernick** [comment]
Thanks!
